name: Test Python client against hazelcast cloud

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: Default is hazelcast, but if you would like to run the workflow with your forked repo, set your github username
        required: true
        default: hazelcast
      branch_name:
        description: Name of the branch to test client from
        required: true
        default: master
      base_url:
        description: Base url of the cloud env. I.e https://uat.hazelcast.cloud
        required: true
        default: https://uat.hazelcast.cloud
      hzVersion:
        description: Version of hazelcast (For cloud standard cluster, it has different versions, i.e 5.0.2-2)
        required: true
        
jobs:
  test_client:
    runs-on: ubuntu-latest
    name: Test Python client against hazelcast cloud
    steps:
      - name: Checkout to scripts
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: Checkout to ${{ github.event.inputs.branch_name }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.organization_name }}/hazelcast-python-client
          path: client
          ref: ${{ github.event.inputs.branch_name }}
          
      - name: Copy the client code to Hazelcast Cloud Test suites
        run: |
          cp -a $GITHUB_WORKSPACE/client/hazelcast $GITHUB_WORKSPACE/HazelcastCloudTests/PythonHazelcastCloudTests/hazelcast

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
        working-directory: HazelcastCloudTests/PythonHazelcastCloudTests
        
      - name: Start RC
        if: ${{ github.event.inputs.base_url }} == 'https://uat.hazelcast.cloud'
        env:
          baseUrl: ${{ github.event.inputs.base_url }} 
          apiKey: ${{ secrets.APIKEY }}
          apiSecret: ${{ secrets.APISECRET }}
        run: |
          python download_server_jars.py --version 5.0 --server-kind os --dst .
          java -jar hazelcast-remote-controller-0.8-SNAPSHOT.jar --use-simple-server &> rc.log &
          
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.11
          
      - name: Run cloud tests
        env: 
          baseUrl: ${{ github.event.inputs.base_url }}
          hzVersion: ${{ github.event.inputs.hzVersion }}
        run: | 
          pytest -o log_cli=true
        working-directory: HazelcastCloudTests/PythonHazelcastCloudTests
          
          
      
