name: Hazelcast cloud test with Java client

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: Default is hazelcast, but if you would like to run the workflow with your forked repo, set your github username
        required: true
        default: hazelcast
      java_client_version:
        description: Java client version without SNAPSHOT suffix
        required: true
      base_url:
        description: Base url of the cloud env. I.e https://uat.hazelcast.cloud
        required: true
        default: https://uat.hazelcast.cloud
      hzVersion:
        description: Version of hazelcast (For cloud standard cluster, it has different versions, i.e 5.0.2-2)
        required: true

jobs:
  test_standard_cluster:
    runs-on: ubuntu-latest
    name: Hazelcast cloud standard cluster tests with Java
    steps:
      - name: Checkout to scripts
        uses: actions/checkout@v2
          
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
          
      - name: Run cloud tests
        env: 
          baseUrl: ${{ github.event.inputs.base_url }}
          apiKey: ${{ secrets.APIKEY_PROD }}
          apiSecret: ${{ secrets.APISECRET_PROD }}
          hzVersion: ${{ github.event.inputs.hzVersion }}
        run: | 
          mvn clean install "-Dhazelcast-version=${{ github.event.inputs.java_client_version }}"
        working-directory: HazelcastCloudTests/javahazelcastcloudtest
