name: Test Server Backwards Compatibility

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: Name of the branch to build JARs from
        required: true
        default: master
      hz_version:
        description: Version of the JARs that will be built, without the SNAPSHOT suffix.
        required: true
        default: 5.0
      run_python:
        description: Set name of the branch of python
        required: true
        default: master
      run_nodejs:
        description: Set name of the branch of nodejs
        required: true
        default: master
      run_cpp:
        description: Set name of the branch of cpp
        required: true
        default: master
      run_csharp:
        description: Set name of the branch of csharp
        required: true
        default: master
      run_go:
        description: Set name of the branch of go
        required: true
        default: master
jobs:
  upload_jars:
    name: Create and upload JARs
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Checkout to Hazelcast
        uses: actions/checkout@v2
        with:
          repository: hazelcast/hazelcast
          path: hazelcast
          ref: ${{ github.event.inputs.branch_name }}
      - name: Checkout to Hazelcast Enterprise
        uses: actions/checkout@v2
        with:
          repository: hazelcast/hazelcast-enterprise
          path: hazelcast-enterprise
          ref: ${{ github.event.inputs.branch_name }}
          token: ${{ secrets.GH_PAT }}
      - name: Build JARs
        run: mvn clean install -DskipTests=True
        working-directory: hazelcast
      - name: Build Enterprise JARs
        run: mvn clean install -DskipTests=True
        working-directory: hazelcast-enterprise
      - name: Upload Hazelcast JAR
        uses: actions/upload-artifact@v2
        with:
          name: hazelcast
          path: hazelcast/hazelcast/target/hazelcast-*[!s].jar
          retention-days: 1
      - name: Upload Hazelcast SQL JAR (if exists)
        uses: actions/upload-artifact@v2
        with:
          name: hazelcast-sql
          path: hazelcast/hazelcast-sql/target/hazelcast-sql-*[!s].jar
          if-no-files-found: ignore
          retention-days: 1
      - name: Upload Hazelcast tests JAR
        uses: actions/upload-artifact@v2
        with:
          name: hazelcast-tests
          path: hazelcast/hazelcast/target/hazelcast-*-tests.jar
          retention-days: 1
      - name: Upload Hazelcast Enterprise JAR
        uses: actions/upload-artifact@v2
        with:
          name: hazelcast-enterprise
          path: hazelcast-enterprise/hazelcast-enterprise/target/hazelcast-enterprise-*[!s].jar
          retention-days: 1
      - name: Upload Hazelcast Enterprise tests JAR
        uses: actions/upload-artifact@v2
        with:
          name: hazelcast-enterprise-tests
          path: hazelcast-enterprise/hazelcast-enterprise/target/hazelcast-enterprise-*-tests.jar
          retention-days: 1

  test_python_clients:
    needs: [ upload_jars ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        server_kind: [ os, enterprise ]
    name: Test Python client ${{ github.event.inputs.run_python }} with ${{ matrix.server_kind }} ${{ github.event.inputs.hz_version }} server
    steps:
      - name: Checkout to scripts
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Checkout to master
        uses: actions/checkout@v2
        with:
          repository: hazelcast/hazelcast-python-client
          path: master
          ref: master
      - name: Checkout to tag
        uses: actions/checkout@v2
        with:
          repository: hazelcast/hazelcast-python-client
          path: tag
          ref: ${{ github.event.inputs.run_python }}
      - name: Copy the client code into master
        run: |
          rm -rf $GITHUB_WORKSPACE/master/hazelcast
          cp -a $GITHUB_WORKSPACE/tag/hazelcast $GITHUB_WORKSPACE/master/hazelcast
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt
        working-directory: master
      - name: Download Hazelcast tests JAR
        uses: actions/download-artifact@v2
        with:
          name: hazelcast-tests
          path: jars
      - name: Download Hazelcast SQL JAR (if exists)
        continue-on-error: true
        uses: actions/download-artifact@v2
        with:
          name: hazelcast-sql
          path: jars
      - name: Download Hazelcast JAR
        if: ${{ matrix.server_kind == 'os' }}
        uses: actions/download-artifact@v2
        with:
          name: hazelcast
          path: jars
      - name: Download Hazelcast Enterprise JAR
        if: ${{ matrix.server_kind == 'enterprise' }}
        uses: actions/download-artifact@v2
        with:
          name: hazelcast-enterprise
          path: jars
      - name: Download Hazelcast Enterprise tests JAR
        if: ${{ matrix.server_kind == 'enterprise' }}
        uses: actions/download-artifact@v2
        with:
          name: hazelcast-enterprise-tests
          path: jars
      - name: Start RC
        env:
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        run: python start_rc.py --rc-version '0.8-SNAPSHOT' --jars jars --server-kind ${{ matrix.server_kind }} --use-simple-server
      - name: Run non-enterprise tests
        if: ${{ matrix.server_kind == 'os' }}
        run: pytest -m 'not enterprise' tests/integration/backward_compatible
        working-directory: master
      - name: Run all tests
        if: ${{ matrix.server_kind == 'enterprise' }}
        run: pytest tests/integration/backward_compatible
        working-directory: master