name: Try to reporduce NearCacheRecoversFromDistortions

on:
  workflow_dispatch:
    inputs:
      organization_name:
        description: Default is hazelcast, but if you would like to run the workflow with your forked repo, set your github username
        required: true
        default: hazelcast
      branch_name:
        description: Name of the branch to test client from
        required: true
        default: master

jobs:
  setup_server_matrix:
    name: Setup the server test matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Checkout to scripts
        uses: actions/checkout@v2
      - name: Set server matrix
        id: set-matrix
        run: echo "::set-output name=matrix::$( python get_server_matrix.py )"
  test_client:
    needs: [setup_server_matrix]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: ${{ fromJson(needs.setup_server_matrix.outputs.matrix) }}
        kind: [enterprise]
        os: [ ubuntu-latest ]
    name: Test NearCacheRecoversFromDistortions against ${{ matrix.kind }} ${{ matrix.version }} server on ${{ matrix.os }}
    steps:
      - name: Checkout to scripts
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup .NET Core 5.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Setup .NET Core 3.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET Core 2.1.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.1.x
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Checkout to ${{ github.event.inputs.branch_name }}
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.organization_name }}/hazelcast-csharp-client
          path: client
          ref: ${{ github.event.inputs.branch_name }}
      - name: Update submodules
        run: |
            git submodule update --init
        working-directory: client
      - name: Build
        shell: pwsh
        run: ./hz.ps1 build
        working-directory: client
      - name: Run all tests
        shell: pwsh
        run: ./hz.ps1 -enterprise -tf "namespace == Hazelcast.Tests.NearCache" -server 5.1 test
        working-directory: client
        env:
          HAZELCAST_ENTERPRISE_KEY: ${{ secrets.HAZELCAST_ENTERPRISE_KEY }}
        
